---
- name: Install Puppet Agent on Debian family
  ansible.builtin.apt:
    name: "{{ puppet_agent_package_name }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install Puppet Agent on RedHat family
  ansible.builtin.dnf:
    name: "{{ puppet_agent_package_name }}"
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Install Puppet Agent on Suse family
  community.general.zypper:
    name: "{{ puppet_agent_package_name }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Suse"

- name: Create Puppet command symlink
  ansible.builtin.file:
    src: "{{ puppet_command_path }}"
    dest: "{{ puppet_command_symlink }}"
    state: link
  when: puppet_manage_command_symlink | bool

- name: Install Puppet Agent on Suse family
  community.general.zypper:
    name: "{{ puppet_agent_package_name }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Suse"
