---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: puppet-agent-rocky9
    image: "molecule-puppet-agent-rocky9"
    dockerfile: Dockerfile
    pre_build_image: false
    privileged: true
    command: "/sbin/init"

provisioner:
  name: ansible

  config_options:
    defaults:
      interpreter_python: auto_silent

verifier:
  name: ansible
